metadata:
  name: bank-service-configs

bank-service:
  cors-allow-host: '*'

server:
  port: 8080
  servlet:
    contextPath: /
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  flyway:
    locations: classpath:/sql
  jpa:
    hibernate:
      ddl-auto: none
