apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: paawak/bank-service:latest
        ports:
        - containerPort: 8080
        env:
          - name: APPLICATION_CONFIG 
            valueFrom:
              configMapKeyRef:
                name: bank-service-configs
                key: application-dev.yml    
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /actuator/health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
