apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: paawak/bank-service:latest
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: bank-service-configs