apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: paawak/bank-service:latest
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
                 path: /actuator/health
                 port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
          volumeMounts:
          - name: common-config
            mountPath: /config/common
      volumes:
      - name: common-config
        configMap:
          name: bank-service-config
