namespace: paawak-bank-app
commonLabels:
  app: bank-service

configMapGenerator:
- name: bank-service-configs
  files:
  - application.properties
  options:
    disableNameSuffixHash: true

resources:
- deployment.yml
- loadbalancer.yml
