namePrefix: bank-service-
commonLabels:
  app: bank-service

configMapGenerator:
- name: app-config
  files:
  - application.yml
  options:
    disableNameSuffixHash: true

resources:
- deployment.yml
- loadbalancer.yml
