apiVersion: v1
kind: Service
metadata:
  name: bank-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: bank-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
