apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: bank-service
          env:
            - name: spring.profiles.active 
              value: dev   

