nameSuffix: -dev
namespace: paawak-bank-app

configMapGenerator:
- name: app-config
  behavior: merge
  files:
  - application-dev.yml

patchesStrategicMerge:
  - deployment-dev.yml

resources:
- ./../../base
