nameSuffix: -dev
namePrefix: bank-service-
namespace: paawak-bank-app
commonLabels:
  app: bank-service

configMapGenerator:
- name: bank-service-config
  behavior: merge
  files:
  - application-dev.yml

patchesStrategicMerge:
  - deployment-dev.yml

resources:
- ./../../base
