nameSuffix: -dev
namespace: paawak-bank-app
commonLabels:
  app: bank-service

configMapGenerator:
- name: bank-service-profile-config
  files:
  - application-dev.yml
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - deployment-dev.yml

resources:
- ./../../base
