--
-- Table structure for table bank_detail
--

CREATE TABLE bank_detail (
  id bigint,
  age smallint,
  job varchar,
  marital varchar,
  education varchar,
  defaulted varchar,
  balance bigint,
  housing varchar,
  loan varchar,
  contact varchar,
  day smallint,
  month varchar,
  duration smallint,
  campaign smallint,
  pdays smallint,
  previous smallint,
  poutcome varchar,
  y varchar,
  
  PRIMARY KEY (id)
);
