apiVersion: v1
kind: Service
metadata:
  name: aws-docker-demo-service
spec:
  type: LoadBalancer
  selector:
    app: aws-docker-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
