apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-docker-demo-deployment
spec:
  selector:
    matchLabels:
      app: aws-docker-demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: aws-docker-demo
    spec:
      containers:
      - name: aws-docker-demo
        image: paawak/aws-docker-demo:latest
        ports:
        - containerPort: 5000
