apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service-deployment
spec:
  selector:
    matchLabels:
      app: bank-service
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: paawak/bank-service:latest
        ports:
        - containerPort: 5000
