version: '3'

services:
    aggregator_1:
        image: paawak/spring-boot-docker-demo:latest
        ports:
          - "8080:8080"
        environment:
          - spring.profiles.active=default
            