FROM openjdk:11.0.8-jre
LABEL author.name="Palash Ray"
LABEL author.email="paawak@gmail.com"
ADD target/spring-boot-docker-demo.jar //
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/spring-boot-docker-demo.jar"]
