spring:
  application:
    name: testcontainer-cassandra-demo	
  cassandra:      
    contact-points: localhost
    ssl: 
      enabled: false
    keyspace-name: testcontainer_demo
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

logging:
  level:
    com.datastax.driver: INFO  
    org.springframework.web: INFO       
