spring:
  application:
    name: testcontainer-cassandra-demo	
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
      contact-points: localhost
      port: 9042
      ssl: false
      keyspace-name: testcontainer_demo
      local-datacenter: datacenter1

logging:
  level:
    com.datastax.driver: INFO  
    org.springframework.web: INFO       
