nameSuffix: -prod
namespace: paawak-bank-app
commonLabels:
  app: bank-service

configMapGenerator:
- name: bank-service-profile-config
  files:
  - application-prod.yml
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - deployment-prod.yml

resources:
- ./../../base
