apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ui
  namespace: paawak-bank-app
  labels:
    app: bank-ui
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: bank-ui
  template:
    metadata:
      labels:
        app: bank-ui
    spec:
      containers:
      - name: bank-ui
        image: paawak/bank-ui:latest
        imagePullPolicy: Always
        env:
          - name: REST_API_BASE_NAME
            value: "http://af8e9cb955ed247a0933197e2431a2ed-150370215.us-east-2.elb.amazonaws.com"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /index.html
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
