apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: paawak/bank-service:latest
        ports:
        - containerPort: 5000
