apiVersion: apps/v1

kind: Deployment

metadata:

  name: bank-service

  namespace: paawak-bank-app

  labels:

    role: api

spec:

  replicas: 2

  strategy:

    type: RollingUpdate

    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 25%

  selector:

    matchLabels:

      role: api

  template:

    metadata:

      labels:

        role: api

    spec:

      containers:

      - name: bank-service

        image: paawak/bank-service:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 5000

        livenessProbe:

          httpGet:

            path: /actuator/health

            port: 5000

          initialDelaySeconds: 2

          periodSeconds: 5

        readinessProbe:

          httpGet:

             path: /actuator/health

             port: 5000

          initialDelaySeconds: 5

          periodSeconds: 5

          successThreshold: 1
