apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: paawak-bank-app
spec:
  type: LoadBalancer
  selector:
    app: bank-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
