spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tesseract-porua
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

logging:
  level:
    liquibase: info

app:
  config:
    batch-size: 200
