spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/druto-chithhi-address-store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
